# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-09-20 05:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='sentence_type',
            field=models.CharField(default=datetime.datetime(2017, 9, 20, 5, 18, 13, 604547, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
